---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: paperless
      version: 8.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  # See https://github.com/k8s-at-home/charts/blob/master/charts/paperless/values.yaml
  values:
    image:
      repository: jonaswinkler/paperless-ng
      tag: 1.5.0

    env:
      PAPERLESS_OCR_LANGUAGE: eng
      PAPERLESS_TIME_ZONE: "Europe/London"
      PAPERLESS_CONSUMER_POLLING: "60"
      PAPERLESS_REDIS: redis://localhost:6379
    persistence:
      data:
        enabled: true
        existingClaim: paperless-data-v1
      media:
        enabled: true
        existingClaim: paperless-media-v1
      consume:
        enabled: true
        existingClaim: paperless-consume-v1
      export:
        enabled: true
        existingClaim: paperless-export-v1

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: "true"
          hajimari.io/icon: "note-multiple"
        hosts:
          - host: "pp.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: paperless-cert
            hosts:
              - "pp.${SECRET_DOMAIN}"

    additionalContainers:
      - name: broker
        image: redis:7.0
        imagePullPolicy: IfNotPresent
