---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: protonmail-bridge
  namespace: notifications
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
  storageClassName: ceph-block
