---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: protonmail-bridge
  namespace: notifications
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: protonmail-bridge
      version: 5.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      # -- image repository
      repository: shenxn/protonmail-bridge
      # -- image tag
      tag: 2.0.1-build
      # -- image pull policy
      pullPolicy: IfNotPresent

    # -- environment variables.
    # @default -- See below
    env:
      # -- Set the container timezone
      TZ: Europe/London

    # -- Configures service settings for the chart.
    # @default -- See values.yaml
    service:
      main:
        ports:
          http:
            enabled: false
          smtp:
            enabled: true
            protocol: TCP
            port: 25

    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      # @default -- See values.yaml
      main:
        enabled: false

    # -- Configure persistence settings for the chart under this key.
    # @default -- See values.yaml
    persistence:
      config:
        enabled: true
        mountPath: /root
        existingClaim: protonmail-bridge
