---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mattermost
  namespace: mattermost
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.mattermost.com
      chart: mattermost-team-edition
      version: 6.1.0
      sourceRef:
        kind: HelmRepository
        name: mattermost-charts
        namespace: flux-system
      interval: 5m
  values:
    fullnameOverride: mattermost
    # image:
    #   repository: ghcr.io/mattermost/mattermost-team-edition
    #   tag: 5.39.0
    mysql:
      mysqlUser:  mattermost
      mysqlDatabase: mattermost
      mysqlPassword: "${SECRET_MATTERMOST_MYSQL_PASSWORD}"

    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      hosts:
        - host: "mm.${SECRET_DOMAIN}"
          paths:
            - path: "/"
              pathType: Prefix
      tls:
        - hosts:
            - "mm.${SECRET_DOMAIN}"
          secretName: "authentik-tls"

    configJSON:
      ServiceSettings:
        SiteURL: "mm.${SECRET_DOMAIN}"
      TeamSettings:
        SiteName: "Mattermost on ${SECRET_DOMAIN}"
