---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-config-pvc
  namespace: vaultwarden
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph-block